### PR TITLE
Enable use of other matrix representations in C code.

### PR DESCRIPTION
**Pull request by LTLA**
This PR allows the use of any double-precision matrix class inside the `fastpath` C code. For example:

```r
library(irlba)
mat <- matrix(data = rnorm(n = 3000*2000), nrow = 3000, ncol = 2000)

set.seed(1000)
ref <- irlba(mat, nv=5)

# Turn off parallelization, otherwise the overhead really slows things down.
library(DelayedArray)
setAutoBPPARAM(SerialParam())

set.seed(1000)
out <- irlba(DelayedArray(mat), nv=5)
identical(ref, out) # TRUE
```

For a bit of context; I was poking around the C code to try to figure out what was going on in #14, and I realized it would be pretty simple to handle arbitrary matrix classes at the C level. So I went ahead and did it, borrowing some ideas from https://github.com/LTLA/beachmat to do so.

The obvious benefit is that you don't have to maintain two parallel code paths that do the same thing. With the benefit of hindsight, this isn't such a clear win because currently you will still have to maintain both R and C versions to support the complex case or `right_only=TRUE`. But the vast majority of use cases will now flow down the `fastpath`, which should make it easier to focus on debugging or improving efficiency or test coverage. And who knows, maybe C-level complex support might come along in version 3 and then the R-based code could be retired entirely.

If this is of any interest, I can document the newly added C functions and add some tests. 

This does nothing to solve #14, BTW.

### CODE REVIEW

**Comment by bwlewis** [comment]
Wow this is a lot to digest, and very promising thanks! Will take me a bit to work through this...

I guess I'm surprised that the incantation of eval to "irlba_mult_single" does not slow things down, but so far in a few quick tests I don't see much difference.

If the performance holds up as it appears to, then I agree with you and don't see why we can't refactor the whole C part to work with any R-defined object that supports matrix vector products and transpose products. This would literally just be a translation of the reference R code into C but maintaining the R data structures, and would avoid some extra copying in the code.

Some related background notes:

- The R version of the algorithm will likely never go away for several reasons. In particular, it's nicer and easier for learning and for others (including me) to tinker with. And I expect several new variations of this algorithm to eventually crop up. For instance, I used to have a block Lanczos variation implemented but removed it because of some technical glitches--I would love to get that back in here. That would help address some of the pathologically bad problems of the current irlba algorithm )which is otherwise very strong).

- The C code is structured so that the core irlba routine only relies, for the most part, on BLAS (or a sparse BLAS). This makes it super-portable to other languages. Mixing in R-specific data structures would make this less easily ported, but I don't have a strong opinion on that really.

**Comment by LTLA** [comment]
Thanks @bwlewis 

> I guess I'm surprised that the incantation of eval to "irlba_mult_single" does not slow things down, but so far in a few quick tests I don't see much difference.

I would guess that's because R's interpreter evaluates expressions in more or less the same way, it's all C under the hood anyway. 

There's probably a cleaner way to get the variables than `installChar(asChar(mkString()))`, but I don't use the raw C API enough to know it. Maybe just `install()`?

> * The R version of the algorithm will likely never go away for several reasons.

Sure, I do the same thing for my C++ functions, mostly for unit testing purposes. 

> * This makes it super-portable to other languages.

If this was a priority, we could do this with loads of macros. 

Anyway, when you get through it, let me know what more you'd like me to do, if anything.

**Comment by alexpghayes** [comment]
> If this was a priority, we could do this with loads of macros.

Can you explain what you mean here? i.e. If you implement a standalone C/C++ library, why does an R package wrapper require lots of macros?

Apologies if this is not the right place for this question.

**Comment by LTLA** [comment]
Hard to known exactly what I was thinking then, but it was probably along these lines: if we wanted a pure C implementation, we would mimic C++ templates with macros to achieve compile-time polymorphism for different matrix representations.

**Pull request closed without merging**
